version: "4.0"

volumes:
  db-app:

services:
  db-app:
    image: postgres:16.0-alpine3.18
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-app:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    restart: unless-stopped
