"""Initial migration

Revision ID: 43349d5ec3e1
Revises: 
Create Date: 2024-07-15 19:24:31.067642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43349d5ec3e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Groups',
    sa.Column('Group_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Group_Name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('Group_ID')
    )
    op.create_table('Teachers',
    sa.Column('Teacher_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('First_Name', sa.String(length=250), nullable=False),
    sa.Column('Last_Name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('Teacher_ID')
    )
    op.create_table('Students',
    sa.Column('Student_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('First_Name', sa.String(length=250), nullable=False),
    sa.Column('Last_Name', sa.String(length=250), nullable=False),
    sa.Column('Date_Of_Birth', sa.Date(), nullable=False),
    sa.Column('Group_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Group_ID'], ['Groups.Group_ID'], ),
    sa.PrimaryKeyConstraint('Student_ID')
    )
    op.create_table('Subjects',
    sa.Column('Subject_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Subject_Name', sa.String(length=250), nullable=False),
    sa.Column('Teacher_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Teacher_ID'], ['Teachers.Teacher_ID'], ),
    sa.PrimaryKeyConstraint('Subject_ID')
    )
    op.create_table('Grades',
    sa.Column('Grade_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Student_ID', sa.Integer(), nullable=False),
    sa.Column('Subject_ID', sa.Integer(), nullable=False),
    sa.Column('Date_Received', sa.DateTime(), nullable=False),
    sa.Column('Grade', sa.Integer(), nullable=False),
    sa.CheckConstraint('"Grade" > 1 AND "Grade" < 7', name='check_grade_between_1_and_7'),
    sa.ForeignKeyConstraint(['Student_ID'], ['Students.Student_ID'], ),
    sa.ForeignKeyConstraint(['Subject_ID'], ['Subjects.Subject_ID'], ),
    sa.PrimaryKeyConstraint('Grade_ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Grades')
    op.drop_table('Subjects')
    op.drop_table('Students')
    op.drop_table('Teachers')
    op.drop_table('Groups')
    # ### end Alembic commands ###
